title: Balı - STEM & Vibe Coding
description: Discover learning through technology and innovation, think creatively, and shape the future.
url: "https://abdbali.github.io"
baseurl: ""
theme: jekyll-theme-minimal # Başlangıç için temiz bir tema
author:
  name: Balı
  email: # E-posta adresin
  youtube: https://www.youtube.com/@abdbali
